#!/usr/bin/env bash
# Configure domain zone so subdomain www points to your load-balancer IP (lb-01)

domainInfo () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  domainInfo "$1" "www"
  domainInfo "$1" "lb-01"
  domainInfo "$1" "web-01"
  domainInfo "$1" "web-02"
elif [ "$#" == 2 ]
then
  domainInfo "$1" "$2"
fi
