#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page
sudo apt-get -y update
sudo apt-get -y install nginx
f=/usr/share/nginx/html/index.html
file=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $f"
service nginx start
line="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $line" $file
sudo service nginx restart
