#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page
sudo apt-get -y update
sudo apt-get -y install nginx
f=/usr/share/nginx/html/index.html
file=/etc/nginx/sites-available/default
sudo bash -c "echo 'Hello World!' > $f"
service nginx start
line="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "30i $line" $file
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
line2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}\n"
sudo sed -i "30i $line2" $file
sudo service nginx restart
