#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Update package lists
sudo apt-get update
# Install HAProxy
sudo apt-get install haproxy -y
# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 34.229.67.59:80 check
    server web-02 52.23.179.66:80 check
EOT
# Test HAProxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
# Start HAProxy
sudo systemctl start haproxy
# Enable HAProxy to start on boot
sudo systemctl enable haproxy
