#!/usr/bin/env bash
# backup.sql contains all my MySQL databases
# dump file has to be compressed to a tar.gz archive
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
