#!/usr/bin/env bash
#displays numbers from 1 to 100
#displays FizzBuzzwhen number is multiple of 3 and 5
#displays Fizz when number is multiple of 3
#displays Buzz when number is multiple of 5

i=1

while [ $i -lt 101 ]
do
	if [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i++))
done
