#!/usr/bin/env bash
#gives information about the school file

namefile=school

if [ -e $namefile ]
then
	echo "school file exists"
else
	echo "school file does not exist"
	exit 1
fi
if [ ! -s $namefile ]
then
	echo "school file is empty"
else
	echo "school file is not empty"
fi
if [ -f $namefile ]
then
	echo "school is a regular file"
fi
